const int WALL = 0;
const int SPACE = 1;
const int START = 2;
const int TARGET = 3;// this is the target that wasn't detected yet
const int BLACK = 4;
const int GRAY = 5;
const int PATH = 6;
const int GRAY_TARGET = 7;// this is the target that was previously detected#pragma once
const int PACMAN = 8;
const int GHOST = 11;
const int GHOST2 = 12;
const int GHOST3 = 13;
const int COIN = 14;
